// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwmSgHGIetCQhZ_8ZRAcAbZPFBaAbNL0',
    appId: '1:841892669443:web:d555b947c5421261150636',
    messagingSenderId: '841892669443',
    projectId: 'ubixstar-f526f',
    authDomain: 'ubixstar-f526f.firebaseapp.com',
    storageBucket: 'ubixstar-f526f.appspot.com',
    measurementId: 'G-0DD22H2SHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4iLjQkOvvcxxfxg3Av3DDRgZ1oHPzX1k',
    appId: '1:841892669443:android:15aeba5aee67a420150636',
    messagingSenderId: '841892669443',
    projectId: 'ubixstar-f526f',
    storageBucket: 'ubixstar-f526f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQhmLLb5sYTpKPs3p_Nr1LUDFuRXzOC1Y',
    appId: '1:841892669443:ios:3a452365df4624ce150636',
    messagingSenderId: '841892669443',
    projectId: 'ubixstar-f526f',
    storageBucket: 'ubixstar-f526f.appspot.com',
    iosBundleId: 'com.example.ubixstarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQhmLLb5sYTpKPs3p_Nr1LUDFuRXzOC1Y',
    appId: '1:841892669443:ios:6ea6f7a61161da7f150636',
    messagingSenderId: '841892669443',
    projectId: 'ubixstar-f526f',
    storageBucket: 'ubixstar-f526f.appspot.com',
    iosBundleId: 'com.example.ubixstarApp.RunnerTests',
  );
}
